---
- hosts: all
  become: true
  tasks:

  - name: copy a file to remote host BIACH!!
    ansible.builtin.copy:
      src: /home/azureuser/inventory
      dest: /home/gddnuser/inventory
  - name: change ownership
    ansible.builtin.file:
      path: /home/gddnuser/inventory
      owner: gddnuser
      group: gddnuser
      mode: '0777' 
